local LogLevels = dofile("scripts/mods/BetterBots/log_levels.lua")

describe("log_levels", function()
	describe("resolve_setting", function()
		it("maps explicit dropdown values", function()
			assert.are.equal(0, LogLevels.resolve_setting("off"))
			assert.are.equal(LogLevels.levels.info, LogLevels.resolve_setting("info"))
			assert.are.equal(LogLevels.levels.debug, LogLevels.resolve_setting("debug"))
			assert.are.equal(LogLevels.levels.trace, LogLevels.resolve_setting("trace"))
		end)

		it("maps legacy checkbox values", function()
			assert.are.equal(LogLevels.levels.debug, LogLevels.resolve_setting(true))
			assert.are.equal(0, LogLevels.resolve_setting(false))
		end)

		it("treats missing setting as off", function()
			assert.are.equal(0, LogLevels.resolve_setting(nil))
		end)
	end)

	describe("should_log", function()
		it("logs info at info and above", function()
			assert.is_true(LogLevels.should_log(LogLevels.levels.info, "info"))
			assert.is_true(LogLevels.should_log(LogLevels.levels.debug, "info"))
			assert.is_true(LogLevels.should_log(LogLevels.levels.trace, "info"))
		end)

		it("filters debug at info level", function()
			assert.is_false(LogLevels.should_log(LogLevels.levels.info, "debug"))
			assert.is_true(LogLevels.should_log(LogLevels.levels.debug, "debug"))
			assert.is_true(LogLevels.should_log(LogLevels.levels.trace, "debug"))
		end)

		it("filters trace at info and debug levels", function()
			assert.is_false(LogLevels.should_log(LogLevels.levels.info, "trace"))
			assert.is_false(LogLevels.should_log(LogLevels.levels.debug, "trace"))
			assert.is_true(LogLevels.should_log(LogLevels.levels.trace, "trace"))
		end)

		it("treats omitted call level as debug", function()
			assert.is_false(LogLevels.should_log(LogLevels.levels.info))
			assert.is_true(LogLevels.should_log(LogLevels.levels.debug))
			assert.is_true(LogLevels.should_log(LogLevels.levels.trace))
		end)

		it("never logs when level is off", function()
			assert.is_false(LogLevels.should_log(0, "info"))
			assert.is_false(LogLevels.should_log(0, "debug"))
			assert.is_false(LogLevels.should_log(0, "trace"))
		end)
	end)

	describe("level_name", function()
		it("maps numeric levels back to names", function()
			assert.are.equal("off", LogLevels.level_name(0))
			assert.are.equal("info", LogLevels.level_name(LogLevels.levels.info))
			assert.are.equal("debug", LogLevels.level_name(LogLevels.levels.debug))
			assert.are.equal("trace", LogLevels.level_name(LogLevels.levels.trace))
		end)
	end)
end)
